import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Toaster as SonnerToaster } from "@/components/ui/sonner"
import MainLayout from "@/components/layout/MainLayout";
import React from "react";
import { Provider } from "@/lib/provider";

const montserrat = Montserrat({ subsets: ["latin"], display: "swap", });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={montserrat.className}>
          <Provider>
            <MainLayout>
              {children}
            </MainLayout>
            <Toaster />
            <SonnerToaster richColors  position="top-center"/>
          </Provider>
        </body>
      </html>
    </>
  );
}
