import type { Metadata } from "next";
import {
  QueryClientProvider,
  QueryClient,
} from '@tanstack/react-query'
import { Montserrat } from "next/font/google";

import "./globals.css";
import { Toaster } from "react-hot-toast";
import { queryClient } from "@/lib/queryclient";
import MainLayout from "@/components/layout/MainLayout";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <body className={montserrat.className}>
          <>
            <MainLayout>
              {children}
            </MainLayout>
            <Toaster />
          </>
        </body>
      </html>
    </QueryClientProvider>
  );
}
